import type {
  Agent,
  Claim,
  Client,
  Payment,
  Plan,
  Policy,
  PolicyMember,
} from "./types";

export const PLANS: Plan[] = [
  {
    id: "plan-tumelo-zinc",
    product_line: "Tumelo Nations Plan",
    tier: "Zinc",
    single_premium: 79,
    family_premium: 89,
    cover_amount: 2000,
    waiting_period_natural: 6,
    waiting_period_accidental: 1,
  },
  {
    id: "plan-tumelo-zinc-plus",
    product_line: "Tumelo Nations Plan",
    tier: "Zinc Plus",
    single_premium: 120,
    family_premium: 129,
    cover_amount: 5000,
    waiting_period_natural: 6,
    waiting_period_accidental: 1,
  },
  {
    id: "plan-tumelo-copper",
    product_line: "Tumelo Nations Plan",
    tier: "Copper",
    single_premium: 159,
    family_premium: 169,
    cover_amount: 10000,
    waiting_period_natural: 6,
    waiting_period_accidental: 1,
  },
  {
    id: "plan-tumelo-bronze",
    product_line: "Tumelo Nations Plan",
    tier: "Bronze",
    single_premium: 199,
    family_premium: 209,
    cover_amount: 15000,
    waiting_period_natural: 6,
    waiting_period_accidental: 1,
  },
  {
    id: "plan-tumelo-silver",
    product_line: "Tumelo Nations Plan",
    tier: "Silver",
    single_premium: 209,
    family_premium: 229,
    cover_amount: 18000,
    waiting_period_natural: 6,
    waiting_period_accidental: 1,
  },
  {
    id: "plan-tumelo-gold",
    product_line: "Tumelo Nations Plan",
    tier: "Gold",
    single_premium: 259,
    family_premium: 279,
    cover_amount: 25000,
    waiting_period_natural: 6,
    waiting_period_accidental: 1,
  },
  {
    id: "plan-tumelo-platinum",
    product_line: "Tumelo Nations Plan",
    tier: "Platinum",
    single_premium: 289,
    family_premium: 299,
    cover_amount: 30000,
    waiting_period_natural: 6,
    waiting_period_accidental: 1,
  },
  {
    id: "plan-uha-copper",
    product_line: "Uhambolwethu Funeral Cover",
    tier: "Copper",
    single_premium: 139,
    family_premium: 149,
    cover_amount: 10000,
    waiting_period_natural: 6,
    waiting_period_accidental: 1,
  },
  {
    id: "plan-uha-bronze",
    product_line: "Uhambolwethu Funeral Cover",
    tier: "Bronze",
    single_premium: 179,
    family_premium: 189,
    cover_amount: 20000,
    waiting_period_natural: 6,
    waiting_period_accidental: 1,
  },
  {
    id: "plan-uha-silver",
    product_line: "Uhambolwethu Funeral Cover",
    tier: "Silver",
    single_premium: 259,
    family_premium: 269,
    cover_amount: 30000,
    waiting_period_natural: 6,
    waiting_period_accidental: 1,
  },
  {
    id: "plan-uha-gold",
    product_line: "Uhambolwethu Funeral Cover",
    tier: "Gold",
    single_premium: 299,
    family_premium: 309,
    cover_amount: 40000,
    waiting_period_natural: 6,
    waiting_period_accidental: 1,
  },
  {
    id: "plan-uha-platinum",
    product_line: "Uhambolwethu Funeral Cover",
    tier: "Platinum",
    single_premium: 389,
    family_premium: 429,
    cover_amount: 50000,
    waiting_period_natural: 6,
    waiting_period_accidental: 1,
  },
];

export const AGENTS: Agent[] = [
  {
    id: "agent-1",
    name: "Tomás Manhiça",
    email: "tomas@britamfuneral.demo",
    phone: "+258 84 123 4567",
    branch: "Johannesburg",
    created_at: "2026-01-15",
  },
  {
    id: "agent-2",
    name: "Beatriz Cossa",
    email: "beatriz@britamfuneral.demo",
    phone: "+258 82 987 6543",
    branch: "Pretoria",
    created_at: "2026-02-01",
  },
];

export const CLIENTS: Client[] = [
  {
    id: "client-1",
    full_name: "Armindo Matsinhe",
    passport_number: "AB1234567",
    date_of_birth: "1985-03-22",
    nationality: "Mozambican",
    phone: "+258 84 111 2233",
    whatsapp_number: "+258 84 111 2233",
    address: "12 Kerk Street",
    city: "Johannesburg",
    province: "Gauteng",
    email: "armindo.m@email.co.za",
    created_by: "agent-1",
    created_at: "2025-12-10",
  },
  {
    id: "client-2",
    full_name: "Graça Abuque",
    passport_number: "CD9876543",
    date_of_birth: "1990-07-14",
    nationality: "Mozambican",
    phone: "+258 82 444 5566",
    whatsapp_number: "+258 82 444 5566",
    address: "88 Stanza Bopape Street",
    city: "Pretoria",
    province: "Gauteng",
    created_by: "agent-2",
    created_at: "2026-01-08",
  },
  {
    id: "client-3",
    full_name: "Felicidade Lopes",
    passport_number: "EF1122334",
    date_of_birth: "1992-11-02",
    nationality: "Mozambican",
    phone: "+258 86 777 8899",
    whatsapp_number: "+258 86 777 8899",
    address: "45 Florida Road",
    city: "Durban",
    province: "KwaZulu-Natal",
    created_by: "agent-1",
    created_at: "2026-03-28",
  },
  {
    id: "client-4",
    full_name: "Domingos Chauque",
    passport_number: "GH5566778",
    date_of_birth: "1978-01-30",
    nationality: "Mozambican",
    phone: "+258 87 222 3344",
    whatsapp_number: "+258 87 222 3344",
    address: "3 Long Street",
    city: "Cape Town",
    province: "Western Cape",
    created_by: "agent-2",
    created_at: "2025-10-20",
  },
  {
    id: "client-5",
    full_name: "Ana Macuácua",
    passport_number: "IJ9988776",
    date_of_birth: "1988-05-18",
    nationality: "Mozambican",
    phone: "+258 84 900 1122",
    whatsapp_number: "+258 84 900 1122",
    address: "210 Main Reef Road",
    city: "Roodepoort",
    province: "Gauteng",
    email: "ana.macuacua@gmail.com",
    created_by: "agent-1",
    created_at: "2026-02-12",
  },
  {
    id: "client-6",
    full_name: "Hélder Tembe",
    passport_number: "KL3344556",
    date_of_birth: "1983-09-09",
    nationality: "Mozambican",
    phone: "+258 85 667 7889",
    whatsapp_number: "+258 85 667 7889",
    address: "56 Von Wielligh Street",
    city: "Johannesburg",
    province: "Gauteng",
    created_by: "agent-1",
    created_at: "2026-03-01",
  },
  {
    id: "client-7",
    full_name: "Carlos Mondlane",
    passport_number: "MN7788990",
    date_of_birth: "1995-12-01",
    nationality: "Mozambican",
    phone: "+258 82 300 4400",
    whatsapp_number: "+258 82 300 4400",
    address: "9 Albertina Sisulu Road",
    city: "Polokwane",
    province: "Limpopo",
    created_by: "agent-2",
    created_at: "2025-11-05",
  },
  {
    id: "client-8",
    full_name: "Maria Zandamela",
    passport_number: "OP4455667",
    date_of_birth: "1991-04-25",
    nationality: "Mozambican",
    phone: "+258 86 121 3141",
    whatsapp_number: "+258 86 121 3141",
    address: "14 Commissioner Street",
    city: "Mbombela",
    province: "Mpumalanga",
    created_by: "agent-1",
    created_at: "2026-04-10",
  },
];

export const POLICIES: Policy[] = [
  {
    id: "policy-1",
    policy_number: "COV-2026-1001",
    client_id: "client-1",
    product_line: "Uhambolwethu Funeral Cover",
    tier: "Platinum",
    premium_type: "monthly",
    base_premium: 389,
    members_premium: 540,
    total_premium: 929,
    account_balance: 0,
    status: "active",
    inception_date: "2026-01-01",
    cover_start_date: "2026-07-01",
    agent_id: "agent-1",
    created_at: "2026-01-01",
  },
  {
    id: "policy-2",
    policy_number: "COV-2026-1002",
    client_id: "client-2",
    product_line: "Tumelo Nations Plan",
    tier: "Gold",
    premium_type: "monthly",
    base_premium: 259,
    members_premium: 220,
    total_premium: 479,
    account_balance: 0,
    status: "active",
    inception_date: "2026-01-15",
    cover_start_date: "2026-07-15",
    agent_id: "agent-2",
    created_at: "2026-01-15",
  },
  {
    id: "policy-3",
    policy_number: "COV-2026-1003",
    client_id: "client-3",
    product_line: "Tumelo Nations Plan",
    tier: "Silver",
    premium_type: "monthly",
    base_premium: 209,
    members_premium: 0,
    total_premium: 209,
    account_balance: 0,
    status: "pending",
    inception_date: "2026-04-01",
    cover_start_date: "2026-10-01",
    agent_id: "agent-1",
    created_at: "2026-04-01",
  },
  {
    id: "policy-4",
    policy_number: "COV-2026-1004",
    client_id: "client-4",
    product_line: "Uhambolwethu Funeral Cover",
    tier: "Bronze",
    premium_type: "monthly",
    base_premium: 179,
    members_premium: 0,
    total_premium: 179,
    account_balance: -358,
    status: "lapsed",
    inception_date: "2025-11-01",
    cover_start_date: "2026-05-01",
    agent_id: "agent-2",
    created_at: "2025-11-01",
  },
  {
    id: "policy-5",
    policy_number: "COV-2026-1005",
    client_id: "client-5",
    product_line: "Tumelo Nations Plan",
    tier: "Bronze",
    premium_type: "monthly",
    base_premium: 199,
    members_premium: 70,
    total_premium: 269,
    account_balance: -120,
    status: "active",
    inception_date: "2026-02-01",
    cover_start_date: "2026-08-01",
    agent_id: "agent-1",
    created_at: "2026-02-01",
  },
  {
    id: "policy-6",
    policy_number: "COV-2026-1006",
    client_id: "client-6",
    product_line: "Tumelo Nations Plan",
    tier: "Copper",
    premium_type: "monthly",
    base_premium: 159,
    members_premium: 250,
    total_premium: 409,
    account_balance: 0,
    status: "active",
    inception_date: "2025-12-01",
    cover_start_date: "2026-06-01",
    agent_id: "agent-1",
    created_at: "2025-12-01",
  },
  {
    id: "policy-7",
    policy_number: "COV-2026-1007",
    client_id: "client-7",
    product_line: "Uhambolwethu Funeral Cover",
    tier: "Silver",
    premium_type: "annual",
    base_premium: 259,
    members_premium: 0,
    total_premium: 2849,
    account_balance: 0,
    status: "cancelled",
    inception_date: "2025-08-01",
    cover_start_date: "2026-02-01",
    agent_id: "agent-2",
    created_at: "2025-08-01",
  },
  {
    id: "policy-8",
    policy_number: "COV-2026-1008",
    client_id: "client-8",
    product_line: "Tumelo Nations Plan",
    tier: "Zinc Plus",
    premium_type: "monthly",
    base_premium: 120,
    members_premium: 220,
    total_premium: 340,
    account_balance: 50,
    status: "active",
    inception_date: "2026-03-10",
    cover_start_date: "2026-09-10",
    agent_id: "agent-1",
    created_at: "2026-03-10",
  },
];

export const MEMBERS: PolicyMember[] = [
  {
    id: "member-1",
    policy_id: "policy-1",
    full_name: "Elsa Matsinhe",
    relationship: "Spouse",
    date_of_birth: "1987-06-11",
    id_or_passport: "AB7654321",
    addon_cost: 220,
    cover_amount: 5000,
    cover_percentage: 10,
    status: "active",
  },
  {
    id: "member-2",
    policy_id: "policy-1",
    full_name: "Lucas Matsinhe",
    relationship: "Child",
    date_of_birth: "2016-04-10",
    id_or_passport: "CH8899001",
    addon_cost: 70,
    cover_amount: 2000,
    cover_percentage: 4,
    status: "active",
  },
  {
    id: "member-3",
    policy_id: "policy-1",
    full_name: "Alberto Chauque",
    relationship: "Parent",
    date_of_birth: "1955-02-28",
    id_or_passport: "GH5544332",
    addon_cost: 250,
    cover_amount: 10000,
    cover_percentage: 20,
    status: "active",
  },
  {
    id: "member-4",
    policy_id: "policy-2",
    full_name: "João Abuque",
    relationship: "Spouse",
    date_of_birth: "1988-09-19",
    id_or_passport: "CD5544332",
    addon_cost: 220,
    cover_amount: 5000,
    cover_percentage: 20,
    status: "inactive",
  },
  {
    id: "member-5",
    policy_id: "policy-5",
    full_name: "Ricardo Macuácua",
    relationship: "Child",
    date_of_birth: "2014-01-20",
    id_or_passport: "IJ0011223",
    addon_cost: 70,
    cover_amount: 2000,
    cover_percentage: 13,
    status: "active",
  },
  {
    id: "member-6",
    policy_id: "policy-6",
    full_name: "Filipe Tembe",
    relationship: "Parent",
    date_of_birth: "1950-11-05",
    id_or_passport: "KL9900112",
    addon_cost: 250,
    cover_amount: 10000,
    cover_percentage: 40,
    status: "active",
  },
];

export const PAYMENTS: Payment[] = [
  {
    id: "pay-1",
    policy_id: "policy-1",
    amount: 929,
    payment_date: "2026-02-05",
    method: "M-Pesa",
    mpesa_reference: "QK7B2MN9PL",
    status: "confirmed",
    month_covered: "2026-02",
  },
  {
    id: "pay-2",
    policy_id: "policy-1",
    amount: 929,
    payment_date: "2026-03-06",
    method: "M-Pesa",
    mpesa_reference: "QK3H9XK2LM",
    status: "confirmed",
    month_covered: "2026-03",
  },
  {
    id: "pay-3",
    policy_id: "policy-2",
    amount: 479,
    payment_date: "2026-02-12",
    method: "M-Pesa",
    mpesa_reference: "QK8N4PQ1RS",
    status: "confirmed",
    month_covered: "2026-02",
  },
  {
    id: "pay-4",
    policy_id: "policy-2",
    amount: 479,
    payment_date: "2026-03-14",
    method: "M-Pesa",
    mpesa_reference: "QK2T5UV8WX",
    status: "confirmed",
    month_covered: "2026-03",
  },
  {
    id: "pay-5",
    policy_id: "policy-4",
    amount: 179,
    payment_date: "2026-02-01",
    method: "M-Pesa",
    mpesa_reference: "QK9A1BC3DE",
    status: "failed",
    month_covered: "2026-02",
    notes: "Insufficient funds",
  },
  {
    id: "pay-6",
    policy_id: "policy-5",
    amount: 269,
    payment_date: "2026-03-02",
    method: "M-Pesa",
    mpesa_reference: "QK4F6GH7JK",
    status: "confirmed",
    month_covered: "2026-03",
  },
  {
    id: "pay-7",
    policy_id: "policy-6",
    amount: 409,
    payment_date: "2026-02-28",
    method: "M-Pesa",
    mpesa_reference: "QK1M2N3O4P",
    status: "confirmed",
    month_covered: "2026-02",
  },
  {
    id: "pay-8",
    policy_id: "policy-6",
    amount: 409,
    payment_date: "2026-04-01",
    method: "M-Pesa",
    mpesa_reference: "QK5Q6R7S8T",
    status: "pending",
    month_covered: "2026-04",
  },
  {
    id: "pay-9",
    policy_id: "policy-8",
    amount: 340,
    payment_date: "2026-04-05",
    method: "Manual",
    status: "confirmed",
    month_covered: "2026-04",
    notes: "Cash at branch",
  },
  {
    id: "pay-10",
    policy_id: "policy-1",
    amount: 929,
    payment_date: "2026-04-04",
    method: "M-Pesa",
    mpesa_reference: "QKU9V0W1X2",
    status: "confirmed",
    month_covered: "2026-04",
  },
  {
    id: "pay-11",
    policy_id: "policy-5",
    amount: 269,
    payment_date: "2026-04-07",
    method: "M-Pesa",
    mpesa_reference: "QKY3Z4A5B6",
    status: "confirmed",
    month_covered: "2026-04",
  },
  {
    id: "pay-12",
    policy_id: "policy-3",
    amount: 209,
    payment_date: "2026-04-02",
    method: "M-Pesa",
    mpesa_reference: "QKC7D8E9F0",
    status: "confirmed",
    month_covered: "2026-04",
  },
];

export const CLAIMS: Claim[] = [
  {
    id: "claim-1",
    policy_id: "policy-2",
    member_id: "member-4",
    deceased_name: "João Abuque",
    relationship: "Spouse",
    cause_of_death: "Natural",
    date_of_death: "2026-02-08",
    status: "paid",
    claim_amount: 25000,
    submitted_at: "2026-02-10T09:00:00",
    reviewed_at: "2026-02-25T14:00:00",
    paid_at: "2026-03-01T10:30:00",
  },
  {
    id: "claim-2",
    policy_id: "policy-6",
    member_id: "member-6",
    deceased_name: "Filipe Tembe",
    relationship: "Parent",
    cause_of_death: "Accidental",
    date_of_death: "2026-04-18",
    status: "under_review",
    claim_amount: 10000,
    submitted_at: "2026-04-20T11:15:00",
  },
  {
    id: "claim-3",
    policy_id: "policy-1",
    deceased_name: "Armindo Matsinhe",
    relationship: "Principal",
    cause_of_death: "Natural",
    date_of_death: "2026-04-25",
    status: "submitted",
    claim_amount: 50000,
    submitted_at: "2026-04-28T16:45:00",
  },
  {
    id: "claim-4",
    policy_id: "policy-4",
    deceased_name: "Domingos Chauque",
    relationship: "Principal",
    cause_of_death: "Natural",
    date_of_death: "2026-04-01",
    status: "rejected",
    claim_amount: 20000,
    submitted_at: "2026-04-05T08:00:00",
    reviewed_at: "2026-04-06T12:00:00",
    rejection_reason:
      "Policy was lapsed at time of claim submission",
  },
];

export function findPlanByProductAndTier(
  productLine: string,
  tier: string
): Plan | undefined {
  return PLANS.find(
    (p) => p.product_line === productLine && p.tier === tier
  );
}
